In [379]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

# 0. VARIABLES CREADAS

In [381]:
# df = data frame original
# df2 = primera selección de columnas
# df_mine = selección de mis columnas para el análisis exploratorio
# columns_of_interest = selección para conocer valores únicos de df_mine

# 1. LEER CSV

In [383]:
df = pd.read_csv("listings.csv")

In [384]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,269467,https://www.airbnb.com/rooms/269467,20240615011618,2024-06-15,city scrape,Sunny and quiet Loft next to Sagrada Familia,The apartment is a cosy open space with 65 m2....,NaN,https://a0.muscache.com/pictures/a6445a90-94eb...,1411775,...,4.79,4.81,4.67,HUTB-001129,t,3,3,0,0,1.15
1,270197,https://www.airbnb.com/rooms/270197,20240615011618,2024-06-15,city scrape,*monthly stays* 4 Bedroom Apartment near Rambla,Rented only for monthly periods. 4 bedroom apa...,NaN,https://a0.muscache.com/pictures/69907440-d8df...,1414702,...,5.00,5.00,4.50,N/A SOLO ESTANCIAS MENSUALES,f,27,27,0,0,0.02
2,18674,https://www.airbnb.com/rooms/18674,20240615011618,2024-06-15,city scrape,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,Apartment in Barcelona located in the heart of...,https://a0.muscache.com/pictures/13031453/413c...,71615,...,4.68,4.78,4.30,HUTB-002062,t,27,27,0,0,0.30
3,272282,https://www.airbnb.com/rooms/272282,20240615011618,2024-06-15,previous scrape,"CHARMING, VERY SPACIOUS & BEST LOCATED",Very spacious apartment located in a modernist...,Eixample is famous for being home to the major...,https://a0.muscache.com/pictures/monet/Select-...,1425070,...,4.96,4.84,4.80,HUTB003208,f,1,1,0,0,2.84
4,23197,https://www.airbnb.com/rooms/23197,20240615011618,2024-06-15,city scrape,"Forum CCIB DeLuxe, Spacious, Large Balcony, relax","Beautiful spacious apartment, large terrace, 5...","Strategically located in the Parc del Fòrum, a...",https://a0.muscache.com/pictures/miso/Hosting-...,90417,...,4.99,4.62,4.64,HUTB005057,f,1,1,0,0,0.48

In [385]:
list(enumerate(df.columns))

[(0, 'id'),
 (1, 'listing_url'),
 (2, 'scrape_id'),
 (3, 'last_scraped'),
 (4, 'source'),
 (5, 'name'),
 (6, 'description'),
 (7, 'neighborhood_overview'),
 (8, 'picture_url'),
 (9, 'host_id'),
 (10, 'host_url'),
 (11, 'host_name'),
 (12, 'host_since'),
 (13, 'host_location'),
 (14, 'host_about'),
 (15, 'host_response_time'),
 (16, 'host_response_rate'),
 (17, 'host_acceptance_rate'),
 (18, 'host_is_superhost'),
 (19, 'host_thumbnail_url'),
 (20, 'host_picture_url'),
 (21, 'host_neighbourhood'),
 (22, 'host_listings_count'),
 (23, 'host_total_listings_count'),
 (24, 'host_verifications'),
 (25, 'host_has_profile_pic'),
 (26, 'host_identity_verified'),
 (27, 'neighbourhood'),
 (28, 'neighbourhood_cleansed'),
 (29, 'neighbourhood_group_cleansed'),
 (30, 'latitude'),
 (31, 'longitude'),
 (32, 'property_type'),
 (33, 'room_type'),
 (34, 'accommodates'),
 (35, 'bathrooms'),
 (36, 'bathrooms_text'),
 (37, 'bedrooms'),
 (38, 'beds'),
 (39, 'amenities'),
 (40, 'price'),
 (41, 'minimum_nights'),
 (42, 'maximum_nights'),
 (43, 'minimum_minimum_nights'),
 (44, 'maximum_minimum_nights'),
 (45, 'minimum_maximum_nights'),
 (46, 'maximum_maximum_nights'),
 (47, 'minimum_nights_avg_ntm'),
 (48, 'maximum_nights_avg_ntm'),
 (49, 'calendar_updated'),
 (50, 'has_availability'),
 (51, 'availability_30'),
 (52, 'availability_60'),
 (53, 'availability_90'),
 (54, 'availability_365'),
 (55, 'calendar_last_scraped'),
 (56, 'number_of_reviews'),
 (57, 'number_of_reviews_ltm'),
 (58, 'number_of_reviews_l30d'),
 (59, 'first_review'),
 (60, 'last_review'),
 (61, 'review_scores_rating'),
 (62, 'review_scores_accuracy'),
 (63, 'review_scores_cleanliness'),
 (64, 'review_scores_checkin'),
 (65, 'review_scores_communication'),
 (66, 'review_scores_location'),
 (67, 'review_scores_value'),
 (68, 'license'),
 (69, 'instant_bookable'),
 (70, 'calculated_host_listings_count'),
 (71, 'calculated_host_listings_count_entire_homes'),
 (72, 'calculated_host_listings_count_private_rooms'),
 (73, 'calculated_host_listings_count_shared_rooms'),
 (74, 'reviews_per_month')]

# 2. SELECCIÓN DE COLUMNAS

### 1. Columnas seleccionadas

In [388]:
columnas_seleccionadas = [
    "description",
    "name",
    "host_since",
    "host_location",
    "host_is_superhost",
    "host_identity_verified",
    "host_has_profile_pic",
    "neighbourhood_group_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "amenities",
    "price",
    "minimum_nights",
    "maximum_nights",
    "has_availability",
    "availability_30",
    "availability_60",
    "number_of_reviews",
    "last_review",
    "review_scores_rating",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month",
    "license",
    "instant_bookable",
    "listing_url"
]

### 2. Copia DF

In [390]:
df2 = df[columnas_seleccionadas].copy()

In [391]:
df2.head()

,description,name,host_since,host_location,host_is_superhost,host_identity_verified,host_has_profile_pic,neighbourhood_group_cleansed,latitude,longitude,...,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,license,instant_bookable,listing_url
0,The apartment is a cosy open space with 65 m2....,Sunny and quiet Loft next to Sagrada Familia,2011-11-16,"Barcelona, Spain",f,t,t,Eixample,41.401810,2.17610,...,4.74,4.59,4.83,4.79,4.81,4.67,1.15,HUTB-001129,t,https://www.airbnb.com/rooms/269467
1,Rented only for monthly periods. 4 bedroom apa...,*monthly stays* 4 Bedroom Apartment near Rambla,2011-11-16,"Barcelona, Spain",f,t,t,Ciutat Vella,41.379360,2.17376,...,4.00,4.50,5.00,5.00,5.00,4.50,0.02,N/A SOLO ESTANCIAS MENSUALES,f,https://www.airbnb.com/rooms/270197
2,110m2 apartment to rent in Barcelona. Located ...,Huge flat for 8 people close to Sagrada Familia,2010-01-19,"Barcelona, Spain",f,t,t,Eixample,41.405560,2.17262,...,4.35,4.63,4.75,4.68,4.78,4.30,0.30,HUTB-002062,t,https://www.airbnb.com/rooms/18674
3,Very spacious apartment located in a modernist...,"CHARMING, VERY SPACIOUS & BEST LOCATED",2011-11-20,"Barcelona, Spain",t,t,t,Eixample,41.383470,2.15802,...,4.92,4.97,4.94,4.96,4.84,4.80,2.84,HUTB003208,f,https://www.airbnb.com/rooms/272282
4,"Beautiful spacious apartment, large terrace, 5...","Forum CCIB DeLuxe, Spacious, Large Balcony, relax",2010-03-09,"Catalonia, Spain",f,t,t,Sant Martí,41.412432,2.21975,...,4.79,4.89,4.95,4.99,4.62,4.64,0.48,HUTB005057,f,https://www.airbnb.com/rooms/23197

# 3. MI SELECCIÓN

### 1. Columnas seleccionadas

In [394]:
mi_seleccion = [
    "neighbourhood_group_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "price",
    "listing_url"
]

In [395]:
df_mine = df2[mi_seleccion].copy()

### 2. Info data

In [397]:
df_mine.dtypes

neighbourhood_group_cleansed     object
latitude                        float64
longitude                       float64
property_type                    object
room_type                        object
accommodates                      int64
bathrooms                       float64
price                            object
listing_url                      object
dtype: object

### 3. Eliminación filas df donde "price"= nulos

In [399]:
df_mine=df_mine.dropna(subset=['price'])

### 4. Cantidad nulos

In [401]:
df_mine.isnull().sum()

neighbourhood_group_cleansed    0
latitude                        0
longitude                       0
property_type                   0
room_type                       0
accommodates                    0
bathrooms                       7
price                           0
listing_url                     0
dtype: int64

### 5. Localización nulos 'bathroom' trabajando con la df original

In [403]:
url_bathrooms = df_mine.loc[df_mine['bathrooms'].isna(), ['bathrooms', 'listing_url']]

print(url_bathrooms)

       bathrooms                                       listing_url
14617        NaN   https://www.airbnb.com/rooms/939973318879363498
14949        NaN   https://www.airbnb.com/rooms/964339945010102928
15580        NaN  https://www.airbnb.com/rooms/1013268024586260166
15904        NaN  https://www.airbnb.com/rooms/1031002061578844729
17106        NaN  https://www.airbnb.com/rooms/1101999350577324560
18388        NaN  https://www.airbnb.com/rooms/1151404135945744837
18601        NaN  https://www.airbnb.com/rooms/1160842594736431325

### 6. Rellenar con 1 toda la columna de nulos en bathrooms

In [405]:
df_mine['bathrooms'] = df_mine['bathrooms'].fillna(1)
# Comprobación nulos 'bathrooms'
df_mine['bathrooms'].isna().sum()

0

### 7. Valores estadísticos

In [407]:
df_mine.describe()

           latitude     longitude  accommodates     bathrooms
count  15189.000000  15189.000000  15189.000000  15189.000000
mean      41.392132      2.167102      3.583580      1.402495
std        0.013990      0.017551      2.215794      0.830558
min       41.350673      2.091740      1.000000      0.000000
25%       41.381080      2.156630      2.000000      1.000000
50%       41.389947      2.168060      3.000000      1.000000
75%       41.401590      2.177680      5.000000      2.000000
max       41.458092      2.227710     16.000000     50.000000

### 8. Valores únicos de todas las columnas de df_mine

In [409]:
# Columnas específicas para obtener valores únicos
columns_of_interest = [
    'neighbourhood_group_cleansed',
    'property_type',
    'room_type',
    'accommodates',
    'bathrooms'
]

# Obtener y ordenar valores únicos de las columnas especificadas

for column in columns_of_interest:
    if column in df_mine.columns:
        unique_values = df_mine[column].unique()
        if pd.api.types.is_numeric_dtype(df_mine[column]):
            sorted_unique_values = sorted(unique_values, reverse=True)
        else:
            sorted_unique_values = sorted(unique_values)
        print(f"Valores únicos en la columna '{column}':")
        print(sorted_unique_values)
        print()
    else:
        print(f"La columna '{column}' no está en el DataFrame.")

Valores únicos en la columna 'neighbourhood_group_cleansed':
['Ciutat Vella', 'Eixample', 'Gràcia', 'Horta-Guinardó', 'Les Corts', 'Nou Barris', 'Sant Andreu', 'Sant Martí', 'Sants-Montjuïc', 'Sarrià-Sant Gervasi']

Valores únicos en la columna 'property_type':
['Barn', 'Boat', 'Camper/RV', 'Casa particular', 'Earthen home', 'Entire cabin', 'Entire chalet', 'Entire condo', 'Entire guest suite', 'Entire guesthouse', 'Entire home', 'Entire loft', 'Entire place', 'Entire rental unit', 'Entire serviced apartment', 'Entire townhouse', 'Entire vacation home', 'Entire villa', 'Private room', 'Private room in bed and breakfast', 'Private room in boat', 'Private room in casa particular', 'Private room in condo', 'Private room in cottage', 'Private room in dome', 'Private room in guest suite', 'Private room in guesthouse', 'Private room in home', 'Private room in hostel', 'Private room in loft', 'Private room in rental unit', 'Private room in serviced apartment', 'Private room in townhouse', 'Private room in vacation home', 'Private room in villa', 'Room in aparthotel', 'Room in boutique hotel', 'Room in hostel', 'Room in hotel', 'Room in serviced apartment', 'Shared room in bed and breakfast', 'Shared room in boutique hotel', 'Shared room in condo', 'Shared room in floor', 'Shared room in guesthouse', 'Shared room in home', 'Shared room in hostel', 'Shared room in hotel', 'Shared room in rental unit', 'Shared room in serviced apartment', 'Tiny home', 'Yurt']

Valores únicos en la columna 'room_type':
['Entire home/apt', 'Hotel room', 'Private room', 'Shared room']

Valores únicos en la columna 'accommodates':
[16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

Valores únicos en la columna 'bathrooms':
[50.0, 15.0, 13.0, 10.0, 8.0, 7.5, 6.0, 5.5, 5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]

# 3. Modificación de columnas

In [411]:
df_mine.head()

,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,price,listing_url
0,Eixample,41.401810,2.17610,Entire loft,Entire home/apt,2,1.0,$176.00,https://www.airbnb.com/rooms/269467
1,Ciutat Vella,41.379360,2.17376,Entire rental unit,Entire home/apt,6,1.5,$74.00,https://www.airbnb.com/rooms/270197
2,Eixample,41.405560,2.17262,Entire rental unit,Entire home/apt,8,2.0,$257.00,https://www.airbnb.com/rooms/18674
4,Sant Martí,41.412432,2.21975,Entire rental unit,Entire home/apt,5,2.0,$249.00,https://www.airbnb.com/rooms/23197
5,Gràcia,41.405660,2.17015,Entire rental unit,Entire home/apt,6,1.5,$240.00,https://www.airbnb.com/rooms/32711

### 1. neighbourhood_group_cleansed

In [431]:
# Cambio nombre por neighbourhood
df_mine.rename(columns={'neighbourhood_group_cleansed': 'neighbourhood'}, inplace=True)

In [435]:
# Transformar datos (minúsculas, sin acentos, _....etc)
df_mine['neighbourhood'] = df_mine['neighbourhood'].str.lower().str.replace(' ', '_').str.replace('-', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('ascii')

### 2. property_type

In [449]:
# Transformar datos (minúsculas, sin acentos, _....etc)
df_mine['property_type'] = df_mine['property_type'].str.lower().str.replace(' ', '_').str.replace('-', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('ascii')

### 3. room_type

In [461]:
# Transformar datos (minúsculas, sin acentos, _....etc)
df_mine[['neighbourhood', 'room_type']] = df_mine[['neighbourhood', 'room_type']].apply(lambda col: col.str.lower().str.replace(' ', '_').str.replace('-', '_').str.replace('/', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('ascii'))

### 4. price

In [472]:
# Transformar datos y pasar a columna numérica
df_mine['price'] = df_mine['price'].str.replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\fatima\AppData\Local\Temp\ipykernel_4996\3178676595.py:2: SyntaxWarning: invalid escape sequence '\$'
  df_mine['price'] = df_mine['price'].str.replace('[\$,]', '', regex=True).astype(float)

In [474]:
df_mine.head()

,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,price,listing_url
0,eixample,41.401810,2.17610,entire_loft,entire_home_apt,2,1.0,176.0,https://www.airbnb.com/rooms/269467
1,ciutat_vella,41.379360,2.17376,entire_rental_unit,entire_home_apt,6,1.5,74.0,https://www.airbnb.com/rooms/270197
2,eixample,41.405560,2.17262,entire_rental_unit,entire_home_apt,8,2.0,257.0,https://www.airbnb.com/rooms/18674
4,sant_marti,41.412432,2.21975,entire_rental_unit,entire_home_apt,5,2.0,249.0,https://www.airbnb.com/rooms/23197
5,gracia,41.405660,2.17015,entire_rental_unit,entire_home_apt,6,1.5,240.0,https://www.airbnb.com/rooms/32711